name: Feature Request
description: Suggest an idea for ZAP.
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to suggest a way to enhance ZAP! Fill out the form below to provide us with info to help fix the bug.
  - type: textarea
    id: description
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: "A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]"
    validations:
      required: true
  - type: textarea
    id: enhancement
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: |
        If applicable, add screenshots to help explain your enhancement/idea.

        Tip: You can attach files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context about the enhancement here.
    validations:
        required: false
  - type: checkboxes
    id: contribute
    attributes:
      label: Would you like to help fix this issue?
      description: "Just say if you'd like to try and help fix this issue. We'll provide any advice and guidance you need."
      options:
        - label: "Yes"
