name: Release Weekly Docker
on:
  workflow_dispatch:
  repository_dispatch:
    types: 'release-weekly-docker'

jobs:
  publish:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "REL_DATE=$(date +%F)" >> $GITHUB_ENV
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: zapbot
          password: ${{ secrets.ZAPBOT_DOCKER_TOKEN }}
      -
        name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          load: true
          context: docker
          file: docker/Dockerfile-weekly
          tags: |
            owasp/zap2docker-weekly:w${{ env.REL_DATE }}
            owasp/zap2docker-weekly:latest
          build-args: |
            WEBSWING_URL=${{ secrets.WEBSWING_URL }}
      - run: docker push owasp/zap2docker-weekly:w${{ env.REL_DATE }}
      - run: docker push owasp/zap2docker-weekly:latest